"""Compiles `hex_expansion_math.md`'s *revised* `HexIndexOf` pseudocode (the `for_number`/
`jump`/`label` restructuring, dead-`ry`-branch removal, and coordinate-subtract simplification)
through `compiler.AstCompiler`, and runs the result via `Interpreter` -- the real
`data/instructions.lua`, not a hand reimplementation -- against the same reference coordinates
`test_hex_expansion.py` already trusts (generated by the in-game-validated `HexAt` sub-behavior
embedded in `HexIndexOf_test_1.dsc`). This is a from-scratch build of the revised design, not the
hand-authored `HexIndexOf_test_1.dsc` itself -- see hex_expansion_math.md's "Open items" note on
why the two now diverge (the `.dsc` still reflects the original, pre-review design).
"""

from pathlib import Path

import pytest

from desynced_toolkit import AstCompiler, Interpreter

DATA_DIR = Path(__file__).parent / "data"

D_HALF = 5
ORIGIN = (0, 0)

# Mirrors hex_expansion_math.md's revised `HexIndexOf(Coord, Origin, d_half) -> (R, T)` pseudocode
# almost verbatim -- differences are noted inline. `Coord`/`Origin`/`d_half` are seeded directly
# into their memory slots by the test fixture below (this compiler doesn't support declared
# sub-behavior parameters yet -- see the module docstring's "Not yet supported" list), and
# `R_out`/`T_out` are read back the same way.
HEXINDEXOF_SRC = """
FourK = 34640
SCALE = 10000
K = 8660

Den = FourK * d_half

Delta = Coord - Origin
dx, dy = separate_coordinate(Delta)

q_num = 2*K*dx - SCALE*dy
r_num = 2*SCALE*dy
yc_num = 0 - q_num - r_num

rx = (2*q_num + Den) // (2*Den)
ry = (2*yc_num + Den) // (2*Den)
rz = (2*r_num + Den) // (2*Den)

err_x = abs(rx*Den - q_num)
err_y = abs(ry*Den - yc_num)
err_z = abs(rz*Den - r_num)

if err_x > err_y and err_x > err_z:
    rx = 0 - ry - rz
elif err_z >= err_y:
    rz = 0 - rx - ry

q = rx
r = rz
absq = abs(q)
absr = abs(r)
absqr = abs(q + r)
Rring = max(absq, absr, absqr)

if Rring == 0:
    R_out = 0
    T_out = 0
    jump(999)

Rminus1 = Rring - 1
negR = 0 - Rring

for k in range(0, 6):
    jump(k)

    label(0)
    if r != Rring:
        continue
    t = q + Rring
    label(100)
    if t < 0:
        continue
    if t > Rminus1:
        continue
    R_out = Rring
    T_out = k * Rring + t
    break

    label(1)
    if q + r != Rring:
        continue
    t = q
    jump(100)

    label(2)
    if q != Rring:
        continue
    t = 0 - r
    jump(100)

    label(3)
    if r != negR:
        continue
    t = Rring - q
    jump(100)

    label(4)
    if q + r != negR:
        continue
    t = 0 - q
    jump(100)

    label(5)
    if q != negR:
        continue
    t = r
    jump(100)

label(999)
"""


def _rt_cases(max_r=8):
    for r in range(0, max_r + 1):
        for t in range(0, max(6 * r, 1)):
            if r == 0 and t > 0:
                continue
            yield r, t


@pytest.fixture(scope="module")
def hexat(engine):
    s = (DATA_DIR / "HexIndexOf_test_1.dsc").read_text().strip()
    _, prog = engine.decode_dsc(s)
    return prog["dependencies"][1]  # HexAt


@pytest.fixture(scope="module")
def compiled_hexindexof(engine):
    return AstCompiler(engine.lua).compile_source(HEXINDEXOF_SRC, name="HexIndexOf (compiled)")


def _run_compiled_hexindexof(engine, compiled, coord, origin, d_half):
    interp = Interpreter(engine, compiled)
    interp.state.mem[interp.mem.var("Coord")] = engine.new_value(0, coord=coord)
    interp.state.mem[interp.mem.var("Origin")] = engine.new_value(0, coord=origin)
    interp.state.mem[interp.mem.var("d_half")] = engine.new_value(d_half)
    interp.run()
    return interp.mem.read("R_out").num, interp.mem.read("T_out").num


@pytest.mark.parametrize("R,T", list(_rt_cases()))
def test_compiled_hexindexof_roundtrips_hexat(engine, hexat, compiled_hexindexof, R, T):
    interp1 = Interpreter(engine, hexat, params={1: R, 2: T, 4: ORIGIN, 5: D_HALF})
    interp1.run()
    coord = interp1.read_param(3)
    xy = (coord.coord.x, coord.coord.y)

    r2, t2 = _run_compiled_hexindexof(engine, compiled_hexindexof, xy, ORIGIN, D_HALF)
    assert (r2, t2) == (R, T)
